apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-server
  annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080