apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: us.gcr.io/durable-spot-354112/jenkins_tools
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080

